from typing import Any, TypedDict, Optional


class AgentState(TypedDict):
    user_input: Optional[str]
    pending_confirmation: Optional[str]
    budget: Optional[float]
    location: Optional[str]
    next_step: Optional[str]
    payment_type: Optional[str]
    payment_type_confirmed: Optional[bool]   # ← NEW: ensures payment type is always verified with user
    Downpayment: Optional[float]
    monthlyinstall: Optional[float]
    budget_valid: Optional[bool]
    breakingbudget: Optional[bool]
    breakinginstallments: Optional[bool]
    candidate_compounds: Optional[list]
    final_compounds: Optional[list[dict[str, Any]]]
    top_compounds: Optional[list[dict[str, Any]]]
    top_developers: Optional[list[dict[str, Any]]]
    typeofproperty: Optional[str]
    final_candidates: Optional[list[dict[str, Any]]]
    features_limit: Optional[int]
    features_force_refresh: Optional[bool]
    compound_features_stats: Optional[dict[str, Any]]
    years: Optional[int]
    ranked_compounds: Optional[list[dict[str, Any]]]
    user_preferences: Optional[dict]
    final_best_compound: Optional[dict[str, Any]]
    selected_compound: Optional[dict[str, Any]]
    candidate_units: Optional[list[dict[str, Any]]]
    final_report: Optional[str]
    abort: Optional[bool]
    embeddings: Optional[str]
    user_id:Optional[str]
    min_price_in_market: Optional[float]
    budget_valid: Optional[bool]
    budget_retry: Optional[bool]

